# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='724_sse.Receiver')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='724_sse.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='supply',
            name='ware_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='724_sse.Ware'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='ware_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='724_sse.Ware'),
        ),
    ]
